# modules/matches.py

HARDCODED_MATCHES = [
    {"match_id": "1", "speeldag": "1", "ronde": "Groep", "groep": "A", "team1": "Mexico", "team2": "Zuid-Afrika", "datum": "11-06-26", "tijd": "21:00", "team1_code": "MX", "team2_code": "ZA"},
    {"match_id": "2", "speeldag": "1", "ronde": "Groep", "groep": "A", "team1": "Zuid-Korea", "team2": "Tsjechië", "datum": "12-06-26", "tijd": "4:00", "team1_code": "KR", "team2_code": "CZ"},
    {"match_id": "3", "speeldag": "1", "ronde": "Groep", "groep": "B", "team1": "Canada", "team2": "Bosnië", "datum": "12-06-26", "tijd": "21:00", "team1_code": "CA", "team2_code": "BA"},
    {"match_id": "4", "speeldag": "1", "ronde": "Groep", "groep": "D", "team1": "Verenigde Staten", "team2": "Paraguay", "datum": "13-06-26", "tijd": "3:00", "team1_code": "US", "team2_code": "PY"},
    {"match_id": "5", "speeldag": "1", "ronde": "Groep", "groep": "D", "team1": "Australië", "team2": "Turkije", "datum": "13-06-26", "tijd": "6:00", "team1_code": "AU", "team2_code": "TR"},
    {"match_id": "6", "speeldag": "1", "ronde": "Groep", "groep": "B", "team1": "Qatar", "team2": "Zwitserland", "datum": "13-06-26", "tijd": "21:00", "team1_code": "QA", "team2_code": "CH"},
    {"match_id": "7", "speeldag": "1", "ronde": "Groep", "groep": "C", "team1": "Brazilië", "team2": "Marokko", "datum": "14-06-26", "tijd": "0:00", "team1_code": "BR", "team2_code": "MA"},
    {"match_id": "8", "speeldag": "1", "ronde": "Groep", "groep": "C", "team1": "Haïti", "team2": "Schotland", "datum": "14-06-26", "tijd": "3:00", "team1_code": "HT", "team2_code": "GB"},
    {"match_id": "9", "speeldag": "1", "ronde": "Groep", "groep": "E", "team1": "Duitsland", "team2": "Curaçao", "datum": "14-06-26", "tijd": "19:00", "team1_code": "DE", "team2_code": "CW"},
    {"match_id": "10", "speeldag": "1", "ronde": "Groep", "groep": "F", "team1": "Nederland", "team2": "Japan", "datum": "14-06-26", "tijd": "22:00", "team1_code": "NL", "team2_code": "JP"},
    {"match_id": "11", "speeldag": "1", "ronde": "Groep", "groep": "E", "team1": "Ivoorkust", "team2": "Ecuador", "datum": "15-06-26", "tijd": "1:00", "team1_code": "CI", "team2_code": "EC"},
    {"match_id": "12", "speeldag": "1", "ronde": "Groep", "groep": "F", "team1": "Zweden", "team2": "Tunesië", "datum": "15-06-26", "tijd": "4:00", "team1_code": "SE", "team2_code": "TN"},
    {"match_id": "13", "speeldag": "1", "ronde": "Groep", "groep": "H", "team1": "Spanje", "team2": "Kaapverdië", "datum": "15-06-26", "tijd": "18:00", "team1_code": "ES", "team2_code": "CV"},
    {"match_id": "14", "speeldag": "1", "ronde": "Groep", "groep": "G", "team1": "België", "team2": "Egypte", "datum": "15-06-26", "tijd": "21:00", "team1_code": "BE", "team2_code": "EG"},
    {"match_id": "15", "speeldag": "1", "ronde": "Groep", "groep": "H", "team1": "Saoedi-Arabië", "team2": "Uruguay", "datum": "16-06-26", "tijd": "0:00", "team1_code": "SA", "team2_code": "UY"},
    {"match_id": "16", "speeldag": "1", "ronde": "Groep", "groep": "G", "team1": "Iran", "team2": "Nieuw-Zeeland", "datum": "16-06-26", "tijd": "3:00", "team1_code": "IR", "team2_code": "NZ"},
    {"match_id": "17", "speeldag": "1", "ronde": "Groep", "groep": "I", "team1": "Frankrijk", "team2": "Senegal", "datum": "16-06-26", "tijd": "21:00", "team1_code": "FR", "team2_code": "SN"},
    {"match_id": "18", "speeldag": "1", "ronde": "Groep", "groep": "I", "team1": "Irak", "team2": "Noorwegen", "datum": "17-06-26", "tijd": "2:00", "team1_code": "IQ", "team2_code": "NO"},
    {"match_id": "19", "speeldag": "1", "ronde": "Groep", "groep": "J", "team1": "Argentinië", "team2": "Algerije", "datum": "17-06-26", "tijd": "3:00", "team1_code": "AR", "team2_code": "DZ"},
    {"match_id": "20", "speeldag": "1", "ronde": "Groep", "groep": "J", "team1": "Oostenrijk", "team2": "Jordanië", "datum": "17-06-26", "tijd": "6:00", "team1_code": "AT", "team2_code": "JO"},
    {"match_id": "21", "speeldag": "1", "ronde": "Groep", "groep": "K", "team1": "Portugal", "team2": "DR Congo", "datum": "17-06-26", "tijd": "19:00", "team1_code": "PT", "team2_code": "CD"},
    {"match_id": "22", "speeldag": "1", "ronde": "Groep", "groep": "L", "team1": "Engeland", "team2": "Kroatië", "datum": "17-06-26", "tijd": "21:00", "team1_code": "GB", "team2_code": "HR"},
    {"match_id": "23", "speeldag": "1", "ronde": "Groep", "groep": "L", "team1": "Ghana", "team2": "Panama", "datum": "18-06-26", "tijd": "1:00", "team1_code": "GH", "team2_code": "PA"},
    {"match_id": "24", "speeldag": "1", "ronde": "Groep", "groep": "K", "team1": "Oezbekistan", "team2": "Colombia", "datum": "18-06-26", "tijd": "4:00", "team1_code": "UZ", "team2_code": "CO"},
    {"match_id": "25", "speeldag": "2", "ronde": "Groep", "groep": "A", "team1": "Tsjechië", "team2": "Zuid-Afrika", "datum": "18-06-26", "tijd": "18:00", "team1_code": "CZ", "team2_code": "ZA"},
    {"match_id": "26", "speeldag": "2", "ronde": "Groep", "groep": "B", "team1": "Zwitserland", "team2": "Bosnië", "datum": "18-06-26", "tijd": "21:00", "team1_code": "CH", "team2_code": "BA"},
    {"match_id": "27", "speeldag": "2", "ronde": "Groep", "groep": "B", "team1": "Canada", "team2": "Qatar", "datum": "19-06-26", "tijd": "0:00", "team1_code": "CA", "team2_code": "QA"},
    {"match_id": "28", "speeldag": "2", "ronde": "Groep", "groep": "A", "team1": "Mexico", "team2": "Zuid-Korea", "datum": "19-06-26", "tijd": "4:00", "team1_code": "MX", "team2_code": "KR"},
    {"match_id": "29", "speeldag": "2", "ronde": "Groep", "groep": "D", "team1": "Verenigde Staten", "team2": "Australië", "datum": "19-06-26", "tijd": "21:00", "team1_code": "US", "team2_code": "AU"},
    {"match_id": "30", "speeldag": "2", "ronde": "Groep", "groep": "C", "team1": "Schotland", "team2": "Marokko", "datum": "20-06-26", "tijd": "0:00", "team1_code": "GB", "team2_code": "MA"},
    {"match_id": "31", "speeldag": "2", "ronde": "Groep", "groep": "C", "team1": "Brazilië", "team2": "Haïti", "datum": "20-06-26", "tijd": "3:00", "team1_code": "BR", "team2_code": "HT"},
    {"match_id": "32", "speeldag": "2", "ronde": "Groep", "groep": "D", "team1": "Turkije", "team2": "Paraguay", "datum": "20-06-26", "tijd": "6:00", "team1_code": "TR", "team2_code": "PY"},
    {"match_id": "33", "speeldag": "2", "ronde": "Groep", "groep": "F", "team1": "Tunesië", "team2": "Japan", "datum": "20-06-26", "tijd": "6:00", "team1_code": "TN", "team2_code": "JP"},
    {"match_id": "34", "speeldag": "2", "ronde": "Groep", "groep": "F", "team1": "Nederland", "team2": "Zweden", "datum": "20-06-26", "tijd": "19:00", "team1_code": "NL", "team2_code": "SE"},
    {"match_id": "35", "speeldag": "2", "ronde": "Groep", "groep": "E", "team1": "Duitsland", "team2": "Ivoorkust", "datum": "20-06-26", "tijd": "22:00", "team1_code": "DE", "team2_code": "CI"},
    {"match_id": "36", "speeldag": "2", "ronde": "Groep", "groep": "E", "team1": "Ecuador", "team2": "Curaçao", "datum": "21-06-26", "tijd": "2:00", "team1_code": "EC", "team2_code": "CW"},
    {"match_id": "37", "speeldag": "2", "ronde": "Groep", "groep": "H", "team1": "Spanje", "team2": "Saoedi-Arabië", "datum": "21-06-26", "tijd": "18:00", "team1_code": "ES", "team2_code": "SA"},
    {"match_id": "38", "speeldag": "2", "ronde": "Groep", "groep": "G", "team1": "België", "team2": "Iran", "datum": "21-06-26", "tijd": "21:00", "team1_code": "BE", "team2_code": "IR"},
    {"match_id": "39", "speeldag": "2", "ronde": "Groep", "groep": "H", "team1": "Uruguay", "team2": "Kaapverdië", "datum": "22-06-26", "tijd": "0:00", "team1_code": "UY", "team2_code": "CV"},
    {"match_id": "40", "speeldag": "2", "ronde": "Groep", "groep": "G", "team1": "Nieuw-Zeeland", "team2": "Egypte", "datum": "22-06-26", "tijd": "3:00", "team1_code": "NZ", "team2_code": "EG"},
    {"match_id": "41", "speeldag": "2", "ronde": "Groep", "groep": "J", "team1": "Argentinië", "team2": "Oostenrijk", "datum": "22-06-26", "tijd": "19:00", "team1_code": "AR", "team2_code": "AT"},
    {"match_id": "42", "speeldag": "2", "ronde": "Groep", "groep": "I", "team1": "Frankrijk", "team2": "Irak", "datum": "22-06-26", "tijd": "23:00", "team1_code": "FR", "team2_code": "IQ"},
    {"match_id": "43", "speeldag": "2", "ronde": "Groep", "groep": "I", "team1": "Noorwegen", "team2": "Senegal", "datum": "23-06-26", "tijd": "2:00", "team1_code": "NO", "team2_code": "SN"},
    {"match_id": "44", "speeldag": "2", "ronde": "Groep", "groep": "J", "team1": "Jordanië", "team2": "Algerije", "datum": "23-06-26", "tijd": "3:00", "team1_code": "JO", "team2_code": "DZ"},
    {"match_id": "45", "speeldag": "2", "ronde": "Groep", "groep": "K", "team1": "Portugal", "team2": "Oezbekistan", "datum": "23-06-26", "tijd": "19:00", "team1_code": "PT", "team2_code": "UZ"},
    {"match_id": "46", "speeldag": "2", "ronde": "Groep", "groep": "L", "team1": "Engeland", "team2": "Ghana", "datum": "23-06-26", "tijd": "22:00", "team1_code": "GB", "team2_code": "GH"},
    {"match_id": "47", "speeldag": "2", "ronde": "Groep", "groep": "L", "team1": "Panama", "team2": "Kroatië", "datum": "24-06-26", "tijd": "1:00", "team1_code": "PA", "team2_code": "HR"},
    {"match_id": "48", "speeldag": "2", "ronde": "Groep", "groep": "K", "team1": "Colombia", "team2": "DR Congo", "datum": "24-06-26", "tijd": "4:00", "team1_code": "CO", "team2_code": "CD"},
    {"match_id": "49", "speeldag": "3", "ronde": "Groep", "groep": "B", "team1": "Zwitserland", "team2": "Canada", "datum": "24-06-26", "tijd": "21:00", "team1_code": "CH", "team2_code": "CA"},
    {"match_id": "50", "speeldag": "3", "ronde": "Groep", "groep": "B", "team1": "Bosnië", "team2": "Qatar", "datum": "24-06-26", "tijd": "21:00", "team1_code": "BA", "team2_code": "QA"},
    {"match_id": "51", "speeldag": "3", "ronde": "Groep", "groep": "C", "team1": "Marokko", "team2": "Haïti", "datum": "25-06-26", "tijd": "0:00", "team1_code": "MA", "team2_code": "HT"},
    {"match_id": "52", "speeldag": "3", "ronde": "Groep", "groep": "C", "team1": "Schotland", "team2": "Brazilië", "datum": "25-06-26", "tijd": "0:00", "team1_code": "GB", "team2_code": "BR"},
    {"match_id": "53", "speeldag": "3", "ronde": "Groep", "groep": "A", "team1": "Zuid-Afrika", "team2": "Zuid-Korea", "datum": "25-06-26", "tijd": "3:00", "team1_code": "ZA", "team2_code": "KR"},
    {"match_id": "54", "speeldag": "3", "ronde": "Groep", "groep": "A", "team1": "Tsjechië", "team2": "Mexico", "datum": "25-06-26", "tijd": "3:00", "team1_code": "CZ", "team2_code": "MX"},
    {"match_id": "55", "speeldag": "3", "ronde": "Groep", "groep": "E", "team1": "Curaçao", "team2": "Ivoorkust", "datum": "25-06-26", "tijd": "22:00", "team1_code": "CW", "team2_code": "CI"},
    {"match_id": "56", "speeldag": "3", "ronde": "Groep", "groep": "E", "team1": "Ecuador", "team2": "Duitsland", "datum": "25-06-26", "tijd": "22:00", "team1_code": "EC", "team2_code": "DE"},
    {"match_id": "57", "speeldag": "3", "ronde": "Groep", "groep": "F", "team1": "Japan", "team2": "Zweden", "datum": "26-06-26", "tijd": "1:00", "team1_code": "JP", "team2_code": "SE"},
    {"match_id": "58", "speeldag": "3", "ronde": "Groep", "groep": "F", "team1": "Tunesië", "team2": "Nederland", "datum": "26-06-26", "tijd": "1:00", "team1_code": "TN", "team2_code": "NL"},
    {"match_id": "59", "speeldag": "3", "ronde": "Groep", "groep": "D", "team1": "Turkije", "team2": "Verenigde Staten", "datum": "26-06-26", "tijd": "4:00", "team1_code": "TR", "team2_code": "US"},
    {"match_id": "60", "speeldag": "3", "ronde": "Groep", "groep": "D", "team1": "Paraguay", "team2": "Australië", "datum": "26-06-26", "tijd": "4:00", "team1_code": "PY", "team2_code": "AU"},
    {"match_id": "61", "speeldag": "3", "ronde": "Groep", "groep": "I", "team1": "Noorwegen", "team2": "Frankrijk", "datum": "26-06-26", "tijd": "21:00", "team1_code": "NO", "team2_code": "FR"},
    {"match_id": "62", "speeldag": "3", "ronde": "Groep", "groep": "I", "team1": "Senegal", "team2": "Irak", "datum": "26-06-26", "tijd": "21:00", "team1_code": "SN", "team2_code": "IQ"},
    {"match_id": "63", "speeldag": "3", "ronde": "Groep", "groep": "H", "team1": "Kaapverdië", "team2": "Saoedi-Arabië", "datum": "27-06-26", "tijd": "2:00", "team1_code": "CV", "team2_code": "SA"},
    {"match_id": "64", "speeldag": "3", "ronde": "Groep", "groep": "H", "team1": "Uruguay", "team2": "Spanje", "datum": "27-06-26", "tijd": "2:00", "team1_code": "UY", "team2_code": "ES"},
    {"match_id": "65", "speeldag": "3", "ronde": "Groep", "groep": "G", "team1": "Nieuw-Zeeland", "team2": "België", "datum": "27-06-26", "tijd": "5:00", "team1_code": "NZ", "team2_code": "BE"},
    {"match_id": "66", "speeldag": "3", "ronde": "Groep", "groep": "G", "team1": "Egypte", "team2": "Iran", "datum": "27-06-26", "tijd": "5:00", "team1_code": "EG", "team2_code": "IR"},
    {"match_id": "67", "speeldag": "3", "ronde": "Groep", "groep": "L", "team1": "Panama", "team2": "Engeland", "datum": "27-06-26", "tijd": "23:00", "team1_code": "PA", "team2_code": "GB"},
    {"match_id": "68", "speeldag": "3", "ronde": "Groep", "groep": "L", "team1": "Kroatië", "team2": "Ghana", "datum": "27-06-26", "tijd": "23:00", "team1_code": "HR", "team2_code": "GH"},
    {"match_id": "69", "speeldag": "3", "ronde": "Groep", "groep": "K", "team1": "Colombia", "team2": "Portugal", "datum": "28-06-26", "tijd": "1:30", "team1_code": "CO", "team2_code": "PT"},
    {"match_id": "70", "speeldag": "3", "ronde": "Groep", "groep": "K", "team1": "DR Congo", "team2": "Oezbekistan", "datum": "28-06-26", "tijd": "1:30", "team1_code": "CD", "team2_code": "UZ"},
    {"match_id": "71", "speeldag": "3", "ronde": "Groep", "groep": "J", "team1": "Algerije", "team2": "Oostenrijk", "datum": "28-06-26", "tijd": "4:00", "team1_code": "DZ", "team2_code": "AT"},
    {"match_id": "72", "speeldag": "3", "ronde": "Groep", "groep": "J", "team1": "Jordanië", "team2": "Argentinië", "datum": "28-06-26", "tijd": "4:00", "team1_code": "JO", "team2_code": "AR"},
]
